"""Sensor entity descriptions for SDM Meter."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)


@dataclass(frozen=True, kw_only=True)
class SdmSensorEntityDescription(SensorEntityDescription):
    """Class describing SDM sensor entities."""
    precision: int = 2

SENSOR_TYPES = [
    SdmSensorEntityDescription(
        key="l1_neutral_volts",
        name="Phase 1 Spannung L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l2_neutral_volts",
        name="Phase 2 Spannung L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l3_neutral_volts",
        name="Phase 3 Spannung L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l1_current",
        name="Phase 1 Strom",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_current",
        name="Phase 2 Strom",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_current",
        name="Phase 3 Strom",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_power",
        name="Phase 1 Wirkleistung",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l2_power",
        name="Phase 2 Wirkleistung",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l3_power",
        name="Phase 3 Wirkleistung",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l1_volt_amps",
        name="Phase 1 Scheinleistung",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l2_volt_amps",
        name="Phase 2 Scheinleistung",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l3_volt_amps",
        name="Phase 3 Scheinleistung",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l1_volt_amps_reactive",
        name="Phase 1 Blindleistung",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l2_volt_amps_reactive",
        name="Phase 2 Blindleistung",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l3_volt_amps_reactive",
        name="Phase 3 Blindleistung",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l1_power_factor",
        name="Phase 1 Leistungsfaktor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="l2_power_factor",
        name="Phase 2 Leistungsfaktor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="l3_power_factor",
        name="Phase 3 Leistungsfaktor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="l1_phase_angle",
        name="Phase 1 Phasenwinkel",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l2_phase_angle",
        name="Phase 2 Phasenwinkel",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l3_phase_angle",
        name="Phase 3 Phasenwinkel",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="average_line_neutral_volt",
        name="Durchschnittsspannung L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="average_line_current",
        name="Durchschnittsstrom",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="sum_line_currents",
        name="Stromsumme",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="total_system_power",
        name="Gesamtwirkleistung",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_system_volt_amps",
        name="Gesamtscheinleistung",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_system_var",
        name="Gesamtblindleistung",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_system_power_factor",
        name="Gesamtleistungsfaktor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="total_system_phase_angle",
        name="Gesamtphasenwinkel",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="frequency",
        name="Netzfrequenz",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="Hz",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="import_kwh",
        name="Bezug Gesamt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="export_kwh",
        name="Einspeisung Gesamt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="import_varh",
        name="Bezug Blindleistung",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="export_varh",
        name="Einspeisung Blindleistung",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="vah_total",
        name="Scheinleistung Gesamt",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvah",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="ah_total",
        name="Stromsumme Gesamt",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="Ah",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="power_demand",
        name="Wirkleistungsbedarf",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="max_power_demand",
        name="Maximaler Wirkleistungsbedarf",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="va_demand",
        name="Scheinleistungsbedarf",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="max_va_demand",
        name="Maximaler Scheinleistungsbedarf",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="neutral_current_demand",
        name="Neutralstrom Bedarf",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_neutral_current_demand",
        name="Maximaler Neutralstrom Bedarf",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="line1_line2_volts",
        name="Spannung L1-L2",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="line2_line3_volts",
        name="Spannung L2-L3",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="line3_line1_volts",
        name="Spannung L3-L1",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="avg_line_line_volts",
        name="Durchschnittsspannung L-L",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="neutral_current",
        name="Neutralstrom",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_volts_thd",
        name="THD Spannung L1",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_volts_thd",
        name="THD Spannung L2",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_volts_thd",
        name="THD Spannung L3",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_current_thd",
        name="THD Strom L1",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_current_thd",
        name="THD Strom L2",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_current_thd",
        name="THD Strom L3",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="avg_volts_thd",
        name="THD Spannung Durchschnitt",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="avg_current_thd",
        name="THD Strom Durchschnitt",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_current_demand",
        name="Strombedarf L1",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_current_demand",
        name="Strombedarf L2",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_current_demand",
        name="Strombedarf L3",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_l1_current_demand",
        name="Max Strombedarf L1",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_l2_current_demand",
        name="Max Strombedarf L2",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_l3_current_demand",
        name="Max Strombedarf L3",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1l2_volts_thd",
        name="THD Spannung L1-L2",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2l3_volts_thd",
        name="THD Spannung L2-L3",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3l1_volts_thd",
        name="THD Spannung L3-L1",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="avg_line_line_volts_thd",
        name="THD Spannung L-L Durchschnitt",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="total_kwh",
        name="Energie Gesamt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="total_kvarh",
        name="Blindleistung Gesamt",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_import_kwh",
        name="Bezug L1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_import_kwh",
        name="Bezug L2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_import_kwh",
        name="Bezug L3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_export_kwh",
        name="Einspeisung L1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_export_kwh",
        name="Einspeisung L2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_export_kwh",
        name="Einspeisung L3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_total_kwh",
        name="Energie Gesamt L1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_total_kwh",
        name="Energie Gesamt L2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_total_kwh",
        name="Energie Gesamt L3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_import_kvarh",
        name="Bezug Blindleistung L1",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_import_kvarh",
        name="Bezug Blindleistung L2",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_import_kvarh",
        name="Bezug Blindleistung L3",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_export_kvarh",
        name="Einspeisung Blindleistung L1",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_export_kvarh",
        name="Einspeisung Blindleistung L2",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_export_kvarh",
        name="Einspeisung Blindleistung L3",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_total_kvarh",
        name="Blindleistung Gesamt L1",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_total_kvarh",
        name="Blindleistung Gesamt L2",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_total_kvarh",
        name="Blindleistung Gesamt L3",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
]

