"""Sensor entity descriptions for SDM Meter."""
# pylint: disable=unexpected-keyword-arg

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)


@dataclass(frozen=True, kw_only=True)
class SdmSensorEntityDescription(SensorEntityDescription):
    """Class describing SDM sensor entities."""
    precision: int = 2

SENSOR_TYPES = [
    SdmSensorEntityDescription(
        key="l1_neutral_volts",
        name="Phase 1 Voltage L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l2_neutral_volts",
        name="Phase 2 Voltage L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l3_neutral_volts",
        name="Phase 3 Voltage L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l1_current",
        name="Phase 1 Current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_current",
        name="Phase 2 Current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_current",
        name="Phase 3 Current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_power",
        name="Phase 1 Active Power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l2_power",
        name="Phase 2 Active Power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l3_power",
        name="Phase 3 Active Power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l1_volt_amps",
        name="Phase 1 Apparent Power",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l2_volt_amps",
        name="Phase 2 Apparent Power",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l3_volt_amps",
        name="Phase 3 Apparent Power",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l1_volt_amps_reactive",
        name="Phase 1 Reactive Power",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l2_volt_amps_reactive",
        name="Phase 2 Reactive Power",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l3_volt_amps_reactive",
        name="Phase 3 Reactive Power",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="l1_power_factor",
        name="Phase 1 Power Factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="l2_power_factor",
        name="Phase 2 Power Factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="l3_power_factor",
        name="Phase 3 Power Factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="l1_phase_angle",
        name="Phase 1 Phase Angle",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="\u00b0",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l2_phase_angle",
        name="Phase 2 Phase Angle",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="\u00b0",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="l3_phase_angle",
        name="Phase 3 Phase Angle",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="\u00b0",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="average_line_neutral_volt",
        name="Average Voltage L-N",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="average_line_current",
        name="Average Current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="sum_line_currents",
        name="Current Sum",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="total_system_power",
        name="Total Active Power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_system_volt_amps",
        name="Total Apparent Power",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_system_var",
        name="Total Reactive Power",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="var",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_system_power_factor",
        name="Total Power Factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        precision=3,
    ),
    SdmSensorEntityDescription(
        key="total_system_phase_angle",
        name="Total Phase Angle",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="\u00b0",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="frequency",
        name="Frequency",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="Hz",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="import_kwh",
        name="Import Active Energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="export_kwh",
        name="Export Active Energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="import_varh",
        name="Import Reactive Energy",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="export_varh",
        name="Export Reactive Energy",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="vah_total",
        name="Total Apparent Energy",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kVAh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="ah_total",
        name="Total Ampere-Hours",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="Ah",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="power_demand",
        name="Active Power Demand",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="max_power_demand",
        name="Maximum Active Power Demand",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_import_power_demand",
        name="Total Import Power Demand",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="max_total_import_power_demand",
        name="Maximum Import Power Demand",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="total_export_power_demand",
        name="Total Export Power Demand",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="max_total_export_power_demand",
        name="Maximum Export Power Demand",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="va_demand",
        name="Apparent Power Demand",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="max_va_demand",
        name="Maximum Apparent Power Demand",
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="VA",
        precision=0,
    ),
    SdmSensorEntityDescription(
        key="neutral_current_demand",
        name="Neutral Current Demand",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_neutral_current_demand",
        name="Maximum Neutral Current Demand",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="line1_line2_volts",
        name="Voltage L1-L2",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="line2_line3_volts",
        name="Voltage L2-L3",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="line3_line1_volts",
        name="Voltage L3-L1",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="avg_line_line_volts",
        name="Average Voltage L-L",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        precision=1,
    ),
    SdmSensorEntityDescription(
        key="neutral_current",
        name="Neutral Current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_volts_thd",
        name="Voltage THD L1",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_volts_thd",
        name="Voltage THD L2",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_volts_thd",
        name="Voltage THD L3",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_current_thd",
        name="Current THD L1",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_current_thd",
        name="Current THD L2",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_current_thd",
        name="Current THD L3",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="avg_volts_thd",
        name="Average Voltage THD",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="avg_current_thd",
        name="Average Current THD",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_current_demand",
        name="Current Demand L1",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_current_demand",
        name="Current Demand L2",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_current_demand",
        name="Current Demand L3",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_l1_current_demand",
        name="Maximum Current Demand L1",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_l2_current_demand",
        name="Maximum Current Demand L2",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="max_l3_current_demand",
        name="Maximum Current Demand L3",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1l2_volts_thd",
        name="Voltage THD L1-L2",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2l3_volts_thd",
        name="Voltage THD L2-L3",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3l1_volts_thd",
        name="Voltage THD L3-L1",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="avg_line_line_volts_thd",
        name="Average Voltage THD L-L",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="total_kwh",
        name="Total Active Energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="total_kvarh",
        name="Total Reactive Energy",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_import_kwh",
        name="Import Active Energy L1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_import_kwh",
        name="Import Active Energy L2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_import_kwh",
        name="Import Active Energy L3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_export_kwh",
        name="Export Active Energy L1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_export_kwh",
        name="Export Active Energy L2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_export_kwh",
        name="Export Active Energy L3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_total_kwh",
        name="Total Active Energy L1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_total_kwh",
        name="Total Active Energy L2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_total_kwh",
        name="Total Active Energy L3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_import_kvarh",
        name="Import Reactive Energy L1",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_import_kvarh",
        name="Import Reactive Energy L2",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_import_kvarh",
        name="Import Reactive Energy L3",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_export_kvarh",
        name="Export Reactive Energy L1",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_export_kvarh",
        name="Export Reactive Energy L2",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_export_kvarh",
        name="Export Reactive Energy L3",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l1_total_kvarh",
        name="Total Reactive Energy L1",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l2_total_kvarh",
        name="Total Reactive Energy L2",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
    SdmSensorEntityDescription(
        key="l3_total_kvarh",
        name="Total Reactive Energy L3",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kvarh",
        precision=2,
    ),
]
